# Gnip Data Processing

In [1]:
%pylab inline
import pandas as pd
import json
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import urllib2
import numpy as np
import os
import os.path
from scipy import misc
from time import strftime,strptime
import re
import math
import pymysql
import MySQLdb
import os,sys
import gzip, json
from dateutil import parser

Populating the interactive namespace from numpy and matplotlib

##### Note 1: We can use the Classes instead of reimplementing the functions.
##### Note 2: You can use SQLAlchemy instead of generating MySQL queries from a dataframe to insert data into a database.

In [2]:
def getimage(url, full_name):
    """
    Downloads the image and returns and object of that image.
    url: image url.
    full_name: path with file name to save the image.
    """
    if os.path.isfile(full_name):
        return mpimg.imread(full_name)
    
    try:
        f = urllib2.urlopen(url)
    except:
        return None
    
    data = f.read()
    with open(full_name, "wb") as code:
        code.write(data)
    return mpimg.imread(full_name)

def getallimages(panda_name, column_name):
    """
    Downloads a group of images from a panda dataframe.
    panda_name: dataframe object.
    column_name: column containing the url.
    """
    downloaded_images = []
    for row in panda_name.loc[panda_name[column_name].notnull(),column_name]:
        for image in row:
            img = getimage(image[column_name],image[column_name].split('/')[-1])
            if not(img is None):
                downloaded_images.append(img)
    return downloaded_images

def klout_getId(screen_name):
    """
    Gets user's klout id if exists.
    screenname: user
    """
    url = 'http://api.klout.com/v2/identity.json/twitter?screenName={0}&key=memp3ncn4qvp6c8guzjcc8dp'.format(screen_name)    
    try:
        return json.load(urllib2.urlopen(url))
    except:
        return None
    
def klout_getScore(klout_id):
    """
    Gets user's klout score if exists.
    
    klout_id: user's klout id.
    """
    url = 'http://api.klout.com/v2/user.json/{0}/score?key=memp3ncn4qvp6c8guzjcc8dp'.format(kloutId)
    try:
        return json.load(urllib2.urlopen(url))
    except:
        return None
    
def extractImageUrl(cell):
    """
    Gets user's klout id if exists.
    cell: extracts tweets image url out of media object.
    """
    if cell is None:
        return None
    return cell[0]['media_url']

def convertDTToDB(cell):
    """
    Converts the time to a MySQL-friendly url.
    cell: datetime string.
    """
    return strftime('%Y-%m-%d %H:%M:%S', strptime(cell,'%Y-%m-%dT%H:%M:%S.000Z'))
def getOldId(cell):
    """
    Get's the ID of tweet or user from gnip format.
    cell: string contatining id.
    """
    return cell.split(':')[2]

def normalizeTweetText(text):
    """
    Normalize tweet text to a MySQL-friendly format.
    text: text string.
    """
    if text is None or type(text) is float:
        return None
    return re.sub(r'[^\w#:@/\.\-\,]', ' ', text)

## Note that if we may put NULL for any of the attributes
## we should remove the single quotation marks from around them.
def ensureDBNull(cell):
    return 'NULL' if cell is None else ("'" + cell + "'")

def getTweetsInsertQuery(tweets):
    """
    Generate insert queries for tweet objects.
    tweets: tweets dataframe.
    """
    query = ""
    for tweet in tweets:
        temp = "REPLACE INTO tweet VALUES('{0}', '{1}', '{2}', '{3}', {4}, '{5}', {6}, {7}, {8});\n".format(tweet[0],
                                     tweet[1],
                                     tweet[2],
                                     tweet[3],
                                     ensureDBNull(tweet[4]),
                                     tweet[5],
                                     ensureDBNull(tweet[6]),
                                     ensureDBNull(tweet[7]),
                                     ensureDBNull(tweet[8]))
        
        query = "{0}{1}".format(query, temp)                         
    return query

def getUsersInsertQuery(users):
    """
    Generate insert queries for user objects.
    users: users dataframe.
    """
    query = ""
    for user in users:
        temp = "REPLACE INTO user VALUES('{0}', '{1}', {2}, {3}, \
          '{4}', '{5}', '{6}', {7}, '{8}');\n".format(user[0],
                                                   user[1],
                                                   ensureDBNull(user[2]),
                                                   user[3],
                                                   user[4],
                                                   user[5],
                                                   user[6],
                                                   ensureDBNull(user[7]),
                                                   user[8])

        query = "{0}{1}".format(query, temp)                
    return query

def getPlacesInsertQuery(places):
    """
    Generate insert queries for place objects.
    places: tweets dataframe.
    """
    query = ""
    for place in places:
        temp = "REPLACE INTO place VALUES ('{0}', '{1}', '{2}', '{3}');\n".format(place[0],
                                                     place[1],
                                                     place[2],
                                                     place[3])

        query = "{0}{1}".format(query, temp)
    return query


def convertNanToNone(text):
    """
    Change any 'nan' string to None.
    text: text string.
    """
    try:
        if str(text) == 'nan':
            return None
    except:
        pass
    return text

def listToStr(cell):
    """
    Convert a list of strings to one string holds all of them.
    cell: list of strings.
    """
    if cell is None:
        return None
    mystr = "";
    for i in cell:
        try:
            mystr = mystr + "," + str(i)
        except:
            print i
    mystr = "[{0}]".format(mystr[1:])
    return mystr
def getDBInstance(host, user, password, db):
    """
    Returns a mysql db object.
    Parameters are obvious.
    """
    return MySQLdb.connect(host,
                         user,
                         password,
                         db)
def extractHashTags(hashTags):
    """
    Extract hashtags out of hashtag objects list.
    hashTags: hashtags list.
    """
    if hashTags is None or hashTags == []:
        return None
    mylist = ''
    for hashtag in hashTags:
        mylist = mylist + ',' + hashtag['text']
    return mylist[1:]

## This class is written by Dr. Mohanty

In [3]:
class GnipDataProcessor(object):

    def __init__(self, i_path, collection, chunk_size=50):
        self.path = i_path
        self.chunk = []
        self.chunk_size = chunk_size
        self.collection = collection
        self.total_inserts = 0

    def all_files(self):
        for path, dirs, files in os.walk(self.path):
            for f in files:
                yield os.path.join(path, f)
    def iter_files(self):
        file_generator = self.all_files()

        for f in file_generator:
            try:
                gfile = gzip.open(f)
                for line in gfile:
                    self.process_line(line)
                gfile.close()
            except Exception as e:
                # print e
                pass
            if self.chunk != []:
                yield self.chunk
        
        

    def process_line(self, line):
        try:
            if len(self.chunk) > self.chunk_size:
                self.process_chunk()
                self.chunk = []
            if line.strip() != "":
                data = json.loads(line)
                if 'id' in data:
                    # data['postedTime_mongo'] = parser.parse(data['postedTime'])
                    self.chunk.append(line)

        except Exception as e:
            # print "error storing chunk \n"
            # print line, e.msg()
            raise

    def process_chunk(self):
        #for item in self.chunk:
        try:
            #print self.chunk
            self.total_inserts += len(self.chunk)
            # print "Inserted: %d number of docs" % self.total_inserts
        except:
            # print "issue inserting"
            pass

# This code is used to process the json files and extract the needed attributes to get it into the format we need

In [ ]:
insrt = GnipDataProcessor("IRMA Data","", chunk_size=1000)
result = []
mygen = insrt.iter_files()
for i in mygen:
    result.append(i)

In [14]:
## Get the data and put it in a panda dataframe
myjson = []
for i in result[400:500]:
    for j in i:
        try:
            myjson.append(json.loads(j))
        except:
            print j
mypanda = pd.io.json.json_normalize(myjson)

### To eliminate unneccesary columns and modify the needed columns to a suitable format for MySQL.

In [15]:
mydata = mypanda.copy()
mydata = mydata.drop_duplicates(subset = ['id'])
mydata = mydata[['id','postedTime','body','geo.coordinates', 'location.name',
                  'twitter_entities.media','twitter_lang', 'twitter_entities.hashtags','actor.id','actor.preferredUsername',
                  'actor.location.displayName','actor.verified','actor.followersCount','actor.friendsCount',
                  'actor.statusesCount','actor.postedTime', 'location.displayName',
                  'location.twitter_country_code','location.geo.coordinates']]
mydata = mydata.dropna(axis = 0, how = 'all')
mydata = mydata.loc[mydata['id'].notnull()]
mydata = mydata.reset_index(drop = True)
mydata = mydata.rename(index=str, columns={'id' : 'tweet.id', 'geo.coordinates' : 'tweet.coordinates',
                                  'postedTime' : 'tweet.created_at', 'body' : 'tweet.text', 'twitter_lang' : 'tweet.lang',
                                  'twitter_entities.media' : 'tweet.media', 'actor.id' : 'user.id',
                                  'actor.preferredUsername' : 'user.screen_name', 'actor.location.displayName' : 'user.location',
                                  'actor.verified' : 'user.verified', 'actor.followersCount': 'user.followers_count',
                                  'actor.friendsCount' : 'user.friends_count', 'actor.statusesCount' : 'user.statuses_count',
                                  'actor.postedTime' : 'user.created_at', 'twitter_entities.hashtags' : 'tweet.hashtags'})


mydata = mydata.applymap(convertNanToNone)
mydata['tweet.created_at'] = mydata['tweet.created_at'].apply(convertDTToDB)
mydata['user.created_at'] = mydata['user.created_at'].apply(convertDTToDB)
mydata['tweet.coordinates'] = mydata['tweet.coordinates'].apply(convertNanToNone)
mydata['tweet.coordinates'] = mydata['tweet.coordinates'].apply(listToStr)
mydata['tweet.text'] = mydata['tweet.text'].apply(normalizeTweetText)
mydata['user.location'] = mydata['user.location'].apply(normalizeTweetText)
mydata['location.name'] = mydata['location.name'].apply(normalizeTweetText)
mydata['tweet.media'] = mydata['tweet.media'].apply(extractImageUrl)
mydata['tweet.id'] = mydata['tweet.id'].apply(getOldId)
mydata['user.id'] = mydata['user.id'].apply(getOldId)
mydata['tweet.hashtags'] = mydata['tweet.hashtags'].apply(extractHashTags)
mydata['tweet.hashtags'] = mydata['tweet.hashtags'].apply(normalizeTweetText)

### Take needed columns for each type of objects to form tables later on.

In [16]:
tweets = mydata[['tweet.id','tweet.created_at','tweet.text','user.id','tweet.coordinates','location.name','tweet.media','tweet.lang', 'tweet.hashtags']]
tweets

,tweet.id,tweet.created_at,tweet.text,user.id,tweet.coordinates,location.name,tweet.media,tweet.lang,tweet.hashtags
0,916979419482345472,2017-10-08 10:51:44,@birchbox I only received 4 things on my box t...,771830969934438401,None,Bayonet Point,None,en,None
1,916979495156019200,2017-10-08 10:52:02,#roadtrip #throughthewindshield #palmtrees #sk...,757948847184240646,"[27.9736,-82.7643]",Clearwater,None,und,"roadtrip,throughthewindshield,palmtrees,sky,ro..."
2,916979920915521536,2017-10-08 10:53:44,Call #TeamChais 813 928-4308 for all your #T...,24633648,"[27.7625,-82.54583333]",Florida,None,en,"TeamChais,TampaBay,RealEstate"
3,916980269848113152,2017-10-08 10:55:07,@Antiloquy How does that make any fucking sense,815777993733898240,None,Ridge Wood Heights,None,en,None
4,916980733616549889,2017-10-08 10:56:58,News Channel 8 Today is on right now @WFLAEd @...,71023584,None,"The NewsCenter TBO.com, Tampa Tribune, News C...",http://pbs.twimg.com/ext_tw_video_thumb/916980...,en,None
5,916981310165569536,2017-10-08 10:59:15,Come see our newest Bikini Barista Jessy Ju...,2284127615,"[26.96755,-82.07943]",Charlotte Harbor,None,en,relaxfulsunday
6,916981304415178753,2017-10-08 10:59:14,"Is it me u missing,just wondering",2876810176,None,Temple Terrace,None,en,None
7,916969566881943552,2017-10-08 10:12:35,I m never going to the casino again,4833325693,None,East Lake-Orient Park,None,en,None
8,916969658431033345,2017-10-08 10:12:57,And who really cares about him anyway #GoodRi...,773983063936294913,None,Tallevast,None,en,GoodRiddanceJamesWoods
9,916970214474113024,2017-10-08 10:15:10,Officially a tattoo apprentice,4833325693,None,East Lake-Orient Park,None,en,None
10,916970429922734081,2017-10-08 10:16:01,few clouds - gt scattered clouds wind 7mph - ...,123717228,"[29.19,-82.14]",Ocala,None,en,None
11,916970535531069440,2017-10-08 10:16:26,Bro. Kevin works driving truck n in pain walki...,3353600338,"[27.19,-82.37]",Florida,None,en,arthritis
12,916971421473169409,2017-10-08 10:19:58,I ve begun meditating before bed and in the mo...,43561421,"[27.93643886,-82.29177654]",Florida,None,en,None
13,916977380811558913,2017-10-08 10:43:38,Draft legal Nationals went well. Good race. Lo...,41288447,"[27.37315975,-82.45501344]",Florida,None,en,None
14,916977485673312256,2017-10-08 10:44:03,I voted #TWICE - Knock Knock in the #SBSPopAsi...,915344447122153472,None,East Lake-Orient Park,None,en,"TWICE,SBSPopAsia,SBSPopAsiaTWICE"
15,916978406549544960,2017-10-08 10:47:43,La NASA muestra im genes nicas del sat lite m...,77657562,None,Cortez,None,es,None
16,916978639757029376,2017-10-08 10:48:39,Up to 57 Off Hair Services from Amy Knight at...,599549147,"[26.5486,-81.913]",Cypress Lake,None,en,None
17,916974218817961984,2017-10-08 10:31:04,NOW SHOWING At The Movies has come to @my...,518684416,"[27.3251305,-82.5276031]",Sarasota,None,en,None
18,916974466349101056,2017-10-08 10:32:03,#i #must #motivate #find #select #edit #write ...,15939104,"[28.00553087,-82.6861446]",Safety Harbor,None,und,"i,must,motivate,find,select,edit,write,post,sp..."
19,916975424130945024,2017-10-08 10:35:52,Good times with the guys #internationalbeerg...,78102678,"[28.1394,-82.462]",Lutz,None,en,internationalbeergarten
20,916975312122138624,2017-10-08 10:35:25,Alert: STRUCTURE FIRE @ 2201 26 AV S Tac: E Se...,71052378,"[27.74505421,-82.66314484]",St Petersburg,None,fr,None
21,917117581592530944,2017-10-08 20:00:45,K https://t.co/quVDge9gU9,763062400820051968,None,Apollo Beach,None,und,None
22,917117508716548097,2017-10-08 20:00:27,SAT OCT 14TH...THE OFFICIAL FAMU HOMECOMING 2K...,65845929,"[30.4517,-84.2685]",Tallahassee,None,en,None
23,917117442610139137,2017-10-08 20:00:12,"15:52 Temp. 89.2 F, Hum. 80 , Dewp. 80.8 F, Ba...",19511251,"[27.86977674,-82.80524377]",Seminole,None,en,None
24,917117562349113344,2017-10-08 20:00:40,ABBREDARIS,165857230,None,Temple Terrace,None,in,None
25,917117414239887360,2017-10-08 20:00:05,Winning games is too easy when you have the 2 ...,1703452406,None,Elfers,None,en,None
26,917117847645585408,2017-10-08 20:01:48,Found peace in knowing,709195136866111488,None,Bear Creek,None,en,None
27,917117834395779073,2017-10-08 20:01:45,We are seeking 10 vegans/vegetarians/non-dairy...,2194752920,"[30.44031,-84.3204]",Tallahassee,None,en,None
28,917117878461190146,2017-10-08 20:01:56,Pourin one out for the Noles #Rip @ Florida S...,1317266774,"[30.44205964,-84.29744983]",Tallahassee,None,en,Rip
29,917117688316559362,2017-10-08 20:01:10,Sunday football with the boys @ Island Wing Co...,2954433508,"[30.50627006,-84.25380382]",Tallahassee,None,en,None
...,...,...,...,...,...,...,...,...,...
3974,916807931034849280,2017-10-07 23:30:18,We re behind you @JTBrown23 https://t.co/OxYd...,3371654080,None,Egypt Lake-Leto,None,en,None
3975,916807927641575424,2017-10-07 23:30:18,Sunset https://t.co/jp2ZEIzThD,1493092015,None,Lido Beach,http://pbs.twimg.com/media/DLkn8AfWkAAdSLj.jpg,en,None
3976,916808294676779008,2017-10-07 23:31:45,This Kucherov and Stamkos line is so,403111685,None,Lealman,None,de,None
3977,916808312196403200,2017-10-07 23:31:49,@CampagnoloKatie Beautiful https://t.co/jLbpTs...,166348853,None,Greater Northdale,http://pbs.twimg.com/tweet_video_thumb/DLkoSqd...,en,None
3978,916808385672118272,2017-10-07 23:32:07,I saw Grim and Mandy Childhood dream came t...,2568233375,"[27.94182251,-82.45591237]",Tampa,None,en,None
3979,916808415254597632,2017-10-07 23:32:14,https://t.co/odsalLmwn5,311168240,None,Doak Campbell Stadium,http://pbs.twimg.com/media/DLkoWniX0AAzcfS.jpg,und,None
3980,916808414889598977,2017-10-07 23:32:14,guess she brought Mizzou s bad luck down to Fl...,163352168,"[29.65091,-82.3486999]",Gainesville,None,en,None
3981,916808565691682816,2017-10-07 23:32:50,Been ready fa ya ugly ah #MIAvsFSU #The...,739653746095980548,None,Temple Terrace,http://pbs.twimg.com/media/DLkohV-UIAACA54.jpg,en,"MIAvsFSU,TheU,Canes"
3982,916808508095516673,2017-10-07 23:32:36,Icha is our little green alien #didntgetszec...,2758857807,"[27.96033554,-82.44054364]",Tampa,None,en,"didntgetszechuansauce,beenugly"
3983,916808497546788864,2017-10-07 23:32:33,LOL https://t.co/z6I3MLKcCr,2284651774,None,Temple Terrace,None,und,None
3984,916808488747184129,2017-10-07 23:32:31,@NEVRLANDSBand https://t.co/tLCWnurpGG,323227071,None,Oldsmar,None,und,None
3985,916808554216030209,2017-10-07 23:32:47,Who makes a canvas page for a unbook study s...,1540171088,None,Holiday,None,en,empowerPasco
3986,916808690191056896,2017-10-07 23:33:19,Juri Ide flying over the clouds to win the #sa...,3400456365,"[27.37315975,-82.45501344]",Florida,None,en,sarasotawc
3987,916808840770871296,2017-10-07 23:33:55,#Canes are undefeated and the #Noles Suck Agai...,55712090,"[30.43782455,-84.3036184]",Tallahassee,None,en,"Canes,Noles,BeatFSU"
3988,916808642422288385,2017-10-07 23:33:08,@CoachKellyFSU I don t want to see you in a Fl...,2410269635,None,Fish Hawk,None,en,None
3989,916808808604880898,2017-10-07 23:33:48,The Your Life Designed and Organized Series is...,116056938,"[27.9709,-82.4646]",Tampa,None,en,None
3990,916808648004820992,2017-10-07 23:33:09,Miami Hurricanes break the 7 year long losing ...,2156572433,"[30.43782455,-84.3036184]",Tallahassee,None,en,None
3991,916808855958454273,2017-10-07 23:33:59,"Checking it out @ The Pink Piano in Lakeland,...",37548551,"[28.03069864,-81.95727192]",Lakeland,None,en,None
3992,916808874757382144,2017-10-07 23:34:03,@alex18marshall @HNYNUT_BERRIOS Glad he s a se...,2410269635,None,Fish Hawk,None,en,None
3993,916808934408753152,2017-10-07 23:34:18,If i could pick up FSU and move it somewhere c...,454469390,"[30.44205964,-84.29744983]",Tallahassee,None,en,gonoles
3994,916808913525399553,2017-10-07 23:34:13,that liquor got me tripping can i have you girl,3041584536,None,Rubonia,None,en,None
3995,916808890708385792,2017-10-07 23:34:07,1st UM v. FSU game and my little cane heart is...,817595230186864644,"[30.43782455,-84.3036184]",Tallahassee,None,en,None
3996,916808939215388672,2017-10-07 23:34:19,Yummy @ Bamboozle Cafe https://t.co/j1kmfRhzDA,33220637,"[27.9485649,-82.4594604]",Tampa,None,en,None
3997,916809010355032064,2017-10-07 23:34:36,Easy to drink not hoppy or bitter - Drinking a...,2203807681,"[27.4968,-82.5326]",Bradenton,None,en,photo
3998,916809097022005255,2017-10-07 23:34:56,Survived @ Doak S. Campbell Stadium https://t....,35590604,"[30.43782455,-84.3036184]",Tallahassee,None,en,None
3999,916809216823889922,2017-10-07 23:35:25,Happy #Canes fans leaving Doak https://t.co/c2...,37228652,None,Doak Campbell Stadium,http://pbs.twimg.com/ext_tw_video_thumb/916808...,en,Canes
4000,916809392992997378,2017-10-07 23:36:07,"If Neil Diamond isn t singing in heaven, then ...",1332445068,None,Sugarmill Woods,None,en,None
4001,916809463092346880,2017-10-07 23:36:24,I am officially Jerked out #JerkFest #2017 #pu...,480713820,"[26.9386463,-82.05419243]",Punta Gorda,None,en,"JerkFest,puntagorda"
4002,916809580067409921,2017-10-07 23:36:52,Damn this match got real tight. #NintendoWorld...,22808420,None,Oldsmar,None,en,NintendoWorldChampionships
4003,916809363452555265,2017-10-07 23:36:00,If Miami beating us means CK is fired... I m h...,2410269635,None,Fish Hawk,None,en,None

In [17]:
users = mydata[['user.id','user.screen_name','user.location','user.verified','user.followers_count','user.friends_count','user.statuses_count','user.created_at']]
users = users.drop_duplicates(subset = ['user.id'])
users['klout_score'] = [0.0] * len(users)
users

,user.id,user.screen_name,user.location,user.verified,user.followers_count,user.friends_count,user.statuses_count,user.created_at,klout_score
0,771830969934438401,SPNGIRL420,"New Port Richey, FL",False,21,95,242,2016-09-02 22:03:38,0.0
1,757948847184240646,techno_nomadic,"Bushnell, FL",False,35,112,1061,2016-07-26 14:41:01,0.0
2,24633648,TeamChais,"Tampa, Florida",False,3714,3712,18395,2009-03-16 02:23:05,0.0
3,815777993733898240,thescarybeary,Earth,False,36,172,1207,2017-01-02 04:33:24,0.0
4,71023584,WFLAPaulM,"Tampa Bay, FL",True,2992,457,28814,2009-09-02 17:36:44,0.0
5,2284127615,cabaristas,"Port Charlotte, FL",False,1441,150,3293,2014-01-15 16:34:34,0.0
6,2876810176,JoannGuimares,"Tampa, FL",False,24,49,561,2014-11-14 18:35:50,0.0
7,4833325693,alexis_renee18,California Florida,False,206,189,4990,2016-01-30 03:54:30,0.0
8,773983063936294913,geribaby1947,"North Sarasota, FL",False,1190,1684,13374,2016-09-08 20:35:17,0.0
10,123717228,_OcalaFL,"Ocala, FL",False,294,4,31591,2010-03-17 01:04:59,0.0
11,3353600338,TinaSuePatters2,Sarasota Florida,False,741,895,11871,2015-07-01 17:56:15,0.0
12,43561421,JenniCoolWhip,None,False,885,803,12915,2009-05-30 17:33:41,0.0
13,41288447,jaybjackson,"Murfreesboro, TN",False,397,1560,3747,2009-05-20 03:37:46,0.0
14,915344447122153472,RobSherouse,None,False,2,96,17,2017-10-03 22:34:57,0.0
15,77657562,albarocuevas,Ciudadano Universal.,False,743,636,48487,2009-09-27 04:15:00,0.0
16,599549147,SBCFortMyers,"Fort Myers, FL",False,17,1,4661,2012-06-04 20:45:36,0.0
17,518684416,jtalbritton,"West Bradenton, FL",False,266,287,1167,2012-03-08 17:12:30,0.0
18,15939104,willchenus,"Tampa, FL",False,906,1065,3418,2008-08-22 00:37:16,0.0
19,78102678,MikeKoop,"Clearwater,FL",False,446,1327,1742,2009-09-28 19:42:29,0.0
20,71052378,PinellasCo911,"Pinellas County, Florida",False,5589,0,145681,2009-09-02 19:30:43,0.0
21,763062400820051968,PoolPyro,"Florida, USA",False,343,229,8599,2016-08-09 17:20:28,0.0
22,65845929,DJGHOST954,World Wide,False,2631,2209,25909,2009-08-15 06:39:21,0.0
23,19511251,BOHICAR6,"sundial, downtown st pete",False,19,39,2910,2009-01-25 23:44:45,0.0
24,165857230,Stovall_Special,"Tampa, FL",False,997,1396,55076,2010-07-12 18:32:43,0.0
25,1703452406,dgallo_10,cfa,False,681,660,16086,2013-08-27 01:47:12,0.0
26,709195136866111488,daaniellevin,None,False,589,137,2085,2016-03-14 01:51:11,0.0
27,2194752920,EnjoyDivaPops,"Tallahassee, FL",False,280,270,693,2013-11-14 19:35:25,0.0
28,1317266774,Dopepanda97,"Florida, USA",False,580,185,17552,2013-03-30 22:08:29,0.0
29,2954433508,PanCubano11,"Miami, FL",False,24,24,106,2015-01-01 07:15:57,0.0
30,235198054,MoyerM5,Earth,False,725,924,68463,2011-01-07 16:07:45,0.0
...,...,...,...,...,...,...,...,...,...
3935,68394581,Forzaken73,"Puerto Rico, USA",False,389,1463,15601,2009-08-24 12:23:34,0.0
3936,24449033,Fashion_Yogini,"Tampa Bay, FL",False,479,232,1800,2009-03-14 23:24:15,0.0
3939,2669338852,mrwilliams430,"St Petersburg, FL",False,476,706,1089,2014-07-03 21:26:11,0.0
3941,19829398,eflow1906,sunny miami florida,False,1151,541,2131,2009-01-31 20:15:00,0.0
3944,281324688,bshowdaz52,"Evansville, IN",False,273,424,368,2011-04-13 02:28:32,0.0
3947,81987203,Cfrost3,"Orlando, Fl",False,33,274,1638,2009-10-13 02:09:26,0.0
3950,1222796156,LSUCheer,"Baton Rouge, La.",False,4881,132,1201,2013-02-26 19:31:55,0.0
3951,281360505,FrontProofMedia,"St Petersburg, FL",False,4580,1112,14331,2011-04-13 04:17:50,0.0
3952,2225458604,mellmaree,None,False,535,321,1896,2013-12-01 19:17:41,0.0
3954,154912082,JamesNassar,None,False,170,126,2861,2010-06-12 15:22:55,0.0
3956,564133410,JRFromTheSouth,"Macon, GA",False,466,446,5225,2012-04-26 21:24:07,0.0
3957,43004374,k_elso_,"Orlando, FL",False,60,56,11302,2009-05-28 00:23:32,0.0
3958,37681267,pabel_martin,"Washington, DC",False,295,351,3039,2009-05-04 15:22:04,0.0
3964,182042595,preachabrown,"Polk/Lakeland, Fl",False,414,339,3350,2010-08-23 17:57:51,0.0
3965,2586787231,toricarnahan,"Bastrop, TX",False,757,221,31867,2014-06-25 03:20:46,0.0
3969,417593537,kosor_mia,Miami,False,1194,848,3749,2011-11-21 04:20:53,0.0
3970,1924990184,elenaginamariex,"Florida, USA",False,229,625,6111,2013-10-01 23:38:37,0.0
3971,325032297,TKFSU,"Boca Raton, FL",False,629,1293,15236,2011-06-27 16:39:57,0.0
3975,1493092015,Britchy2003Meg,None,False,177,115,1196,2013-06-08 14:34:05,0.0
3979,311168240,KennyP_757,"Portsmouth, Va",False,487,514,102273,2011-06-05 00:48:07,0.0
3980,163352168,not_2DAYY,None,False,960,397,11092,2010-07-06 05:30:18,0.0
3982,2758857807,asvp_leak_,None,False,307,570,6192,2014-09-02 02:07:49,0.0
3987,55712090,BigMoneyRog,"Miami, FL",False,151,439,7017,2009-07-11 00:40:37,0.0
3989,116056938,lindaleubanks,"Tampa, FL Worldwde",False,809,648,5868,2010-02-21 00:47:24,0.0
3990,2156572433,southbchripped,South Florida,False,137,531,5502,2013-10-28 02:10:12,0.0
3993,454469390,ElizabethScinta,KCD 18,False,431,482,2606,2012-01-04 01:21:12,0.0
3994,3041584536,nene_smarr,FAMU,False,2334,1843,13635,2015-02-25 17:15:30,0.0
3995,817595230186864644,dwilliams2992,"Atlanta, GA",False,89,177,594,2017-01-07 04:54:27,0.0
3996,33220637,TheRealMrSteel,"Wesley Chapel, FL",False,88,190,217,2009-04-19 15:10:46,0.0
4000,1332445068,kshaferus,Homosassa FL,False,247,367,695,2013-04-06 20:45:35,0.0

In [18]:
places = mydata[['location.name','location.displayName','location.twitter_country_code','location.geo.coordinates']]
places = places.drop_duplicates(subset = ['location.name'])
# places['location.displayName'] = places['location.displayName'].apply(normalizeTweetText)
places.reset_index(drop = True)
places

,location.name,location.displayName,location.twitter_country_code,location.geo.coordinates
0,Bayonet Point,"Bayonet Point, FL",US,"[[[-82.733975, 28.299909], [-82.733975, 28.350..."
1,Clearwater,"Clearwater, FL",US,"[[[-82.831674, 27.935178], [-82.831674, 28.050..."
2,Florida,"Florida, USA",US,"[[[-87.634643, 24.396308], [-87.634643, 31.001..."
3,Ridge Wood Heights,"Ridge Wood Heights, FL",US,"[[[-82.523307, 27.276661], [-82.523307, 27.298..."
4,"The NewsCenter TBO.com, Tampa Tribune, News C...","The NewsCenter (TBO.com, Tampa Tribune, News C...",US,"[[[-82.460589, 27.944825], [-82.460589, 27.944..."
5,Charlotte Harbor,"Charlotte Harbor, FL",US,"[[[-82.084626, 26.946308], [-82.084626, 26.975..."
6,Temple Terrace,"Temple Terrace, FL",US,"[[[-82.40189, 28.011287], [-82.40189, 28.07369..."
7,East Lake-Orient Park,"East Lake-Orient Park, FL",US,"[[[-82.410125, 27.965019], [-82.410125, 28.031..."
8,Tallevast,"Tallevast, FL",US,"[[[-82.563644, 27.388731], [-82.563644, 27.429..."
10,Ocala,"Ocala, FL",US,"[[[-82.293902, 28.962902], [-82.293902, 29.277..."
15,Cortez,"Cortez, FL",US,"[[[-82.692316, 27.450643], [-82.692316, 27.478..."
16,Cypress Lake,"Cypress Lake, FL",US,"[[[-81.918368, 26.520458], [-81.918368, 26.557..."
17,Sarasota,"Sarasota, FL",US,"[[[-82.588866, 27.293114], [-82.588866, 27.389..."
18,Safety Harbor,"Safety Harbor, FL",US,"[[[-82.712772, 27.977811], [-82.712772, 28.049..."
19,Lutz,"Lutz, FL",US,"[[[-82.502573, 28.090958], [-82.502573, 28.172..."
20,St Petersburg,"St Petersburg, FL",US,"[[[-82.758209, 27.694323], [-82.758209, 27.897..."
21,Apollo Beach,"Apollo Beach, FL",US,"[[[-82.437901, 27.735035], [-82.437901, 27.793..."
22,Tallahassee,"Tallahassee, FL",US,"[[[-84.386548, 30.365093], [-84.386548, 30.587..."
23,Seminole,"Seminole, FL",US,"[[[-82.81611, 27.80979], [-82.81611, 27.884351..."
25,Elfers,"Elfers, FL",US,"[[[-82.739856, 28.193916], [-82.739856, 28.233..."
26,Bear Creek,"Bear Creek, FL",US,"[[[-82.732594, 27.74548], [-82.732594, 27.7630..."
30,Holmes Beach,"Holmes Beach, FL",US,"[[[-82.731197, 27.484796], [-82.731197, 27.527..."
31,Dade City,"Dade City, FL",US,"[[[-82.239194, 28.324759], [-82.239194, 28.408..."
32,Iona,"Iona, FL",US,"[[[-81.99359, 26.491867], [-81.99359, 26.54318..."
33,Treasure Island,"Treasure Island, FL",US,"[[[-82.783299, 27.738608], [-82.783299, 27.786..."
34,Lakeland,"Lakeland, FL",US,"[[[-82.042715, 27.968692], [-82.042715, 28.130..."
36,Holiday,"Holiday, FL",US,"[[[-82.78516, 28.17275], [-82.78516, 28.204041..."
40,Gulf Gate Estates,"Gulf Gate Estates, FL",US,"[[[-82.522638, 27.233261], [-82.522638, 27.276..."
41,Egypt Lake-Leto,"Egypt Lake-Leto, FL",US,"[[[-82.527472, 27.996725], [-82.527472, 28.037..."
42,Victory Field,Victory Field,US,"[[[-81.91801, 28.027215], [-81.91801, 28.02721..."
...,...,...,...,...
3221,GrassLands Brewing Company,GrassLands Brewing Company,US,"[[[-84.290688, 30.435336], [-84.290688, 30.435..."
3235,Boca Grande Swing Bridge,Boca Grande Swing Bridge,US,"[[[-82.270134, 26.827154], [-82.270134, 26.827..."
3268,Sugarmill Woods,"Sugarmill Woods, FL",US,"[[[-82.55312, 28.694598], [-82.55312, 28.76403..."
3328,Ava Restaurant,Ava Restaurant,US,"[[[-82.483068, 27.93622], [-82.483068, 27.9362..."
3338,All Peoples Life Center,All Peoples Life Center,US,"[[[-82.38749, 28.009696], [-82.38749, 28.00969..."
3355,East Bay High School,East Bay High School,US,"[[[-82.362914, 27.792959], [-82.362914, 27.792..."
3367,Vertigo Burger And Fries,Vertigo Burger And Fries,US,"[[[-84.254155, 30.505944], [-84.254155, 30.505..."
3371,Dot Ice - Artisan Rolled Ice Cream,Dot Ice - Artisan Rolled Ice Cream,US,"[[[-82.633841, 27.773814], [-82.633841, 27.773..."
3373,Florida Hospital Center Ice,Florida Hospital Center Ice,US,"[[[-82.380623, 28.195892], [-82.380623, 28.195..."
3385,Dulcet Restaurant Lounge,Dulcet Restaurant & Lounge,US,"[[[-82.719541, 28.249258], [-82.719541, 28.249..."
3417,The Alley at SouthShore,The Alley at SouthShore,US,"[[[-82.341313, 27.79004], [-82.341313, 27.7900..."
3439,"Planet Fitness - Holiday, FL","Planet Fitness - Holiday, FL",US,"[[[-82.738726, 28.198945], [-82.738726, 28.198..."
3452,Hornblasters Truck,Hornblasters Truck!,US,"[[[-82.556043, 27.938858], [-82.556043, 27.938..."
3456,Bare Assets Holiday,Bare Assets Holiday,US,"[[[-82.740166, 28.179396], [-82.740166, 28.179..."
3532,Seven Springs Middle School,Seven Springs Middle School,US,"[[[-82.670371, 28.19511], [-82.670371, 28.1951..."
3570,Gulf of Mexico,Gulf of Mexico,US,"[[[-82.685794, 27.436235], [-82.685794, 27.436..."
3610,"Gainsville, FL","Gainsville, FL",US,"[[[-82.394654, 29.728046], [-82.394654, 29.728..."
3625,Howard Frankland Bridge,Howard Frankland Bridge,US,"[[[-82.589453, 27.92698], [-82.589453, 27.9269..."
3629,Howl-O-Scream,Howl-O-Scream,US,"[[[-82.417268, 28.034482], [-82.417268, 28.034..."
3639,St. George Island Bridge,St. George Island Bridge,US,"[[[-84.888016, 29.717084], [-84.888016, 29.717..."
3643,AJA,AJA,US,"[[[-82.448795, 27.943984], [-82.448795, 27.943..."
3645,Waffle House,Waffle House,US,"[[[-82.150149, 28.025746], [-82.150149, 28.025..."
3682,"David A. Straz, Jr. Center for the Performing ...","David A. Straz, Jr. Center for the Performing ...",US,"[[[-82.464001, 27.951762], [-82.464001, 27.951..."
3687,Seffner Christian Academy,Seffner Christian Academy,US,"[[[-82.303376, 28.000762], [-82.303376, 28.000..."
3688,Pepin Hospitality Center,Pepin Hospitality Center,US,"[[[-82.399509, 27.982382], [-82.399509, 27.982..."
3751,Dunedin Causeway,Dunedin Causeway,US,"[[[-82.799664, 28.050943], [-82.799664, 28.050..."
3864,Fresh Rags,Fresh Rags,US,"[[[-82.701076, 27.841554], [-82.701076, 27.841..."
3914,TECO Line Streetcar - Centennial Park Station,TECO Line Streetcar - Centennial Park Station,US,"[[[-82.437241, 27.960999], [-82.437241, 27.960..."
3944,Venezia,Venezia,US,"[[[-82.577816, 27.318869], [-82.577816, 27.318..."
3975,Lido Beach,Lido Beach,US,"[[[-82.576869, 27.310955], [-82.576869, 27.310..."